sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.10" ] || npm install -g npm'
  - npm config set loglevel warn

before_script:
  - npm install -g bower
  - bower install

script:
    - karma start --single-run
